# Generated by Django 5.2.8 on 2025-11-22 19:51

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import root.upload_path_utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09xxxxxxxxx'. Up to 11 digits allowed.", regex='^09\\d{9}$')], verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('link_text', models.CharField(default='اطلاعات بیشتر دریافت کنید', max_length=100)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g., v1.0.1', max_length=20)),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux_deb', 'Linux (Debian/Ubuntu)'), ('linux_rpm', 'Linux (Fedora/Red Hat)'), ('android', 'Android')], help_text='The target operating system for this file.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Release notes or a short description.')),
                ('release_file', models.FileField(upload_to=root.upload_path_utilities.get_upload_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'upload_date',
                'unique_together': {('version', 'os')},
            },
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('what_you_read', models.TextField(verbose_name='What you read')),
                ('cover_image', models.ImageField(help_text='570x300', upload_to='covers/')),
                ('main_image', models.ImageField(help_text='620x300', upload_to='images/')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.author')),
                ('tags', models.ManyToManyField(to='root.tag')),
            ],
        ),
    ]
