# Generated by Django 5.2.7 on 2025-11-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='name',
            new_name='title',
        ),
    ]
