# Generated by Django 5.2.8 on 2025-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlanBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('is_special', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('benefits', models.ManyToManyField(to='root.premiumplanbenefit')),
            ],
        ),
    ]
