# Generated by Django 5.2.7 on 2025-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_name_usecase_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('link_text', models.CharField(default='اطلاعات بیشتر دریافت کنید', max_length=100)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
