# Generated by Django 5.2.8 on 2025-11-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_author_weblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
