# Generated by Django 5.2.8 on 2025-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_premiumplanbenefit_premiumplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplanbenefit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
