# Generated by Django 5.2.8 on 2025-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_premiumplanbenefit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='discount_precent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
