# Generated by Django 5.2.8 on 2025-11-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_weblog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
