# Generated by Django 5.2.8 on 2025-11-06 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09xxxxxxxxx'. Up to 11 digits allowed.", regex='^09\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='cover_image',
            field=models.ImageField(default=1, help_text='570x300', upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblog',
            name='main_image',
            field=models.ImageField(default=1, help_text='620x300', upload_to='images/'),
            preserve_default=False,
        ),
    ]
