# Generated by Django 5.2.8 on 2025-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_contactmessage_phone_alter_weblog_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g., v1.0.1', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Release notes or a short description.')),
                ('release_file', models.FileField(upload_to='releases/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'upload_date',
            },
        ),
    ]
