# Generated by Django 5.2.8 on 2025-11-06 15:50

import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='os',
            field=models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux_deb', 'Linux (Debian/Ubuntu)'), ('linux_rpm', 'Linux (Fedora/Red Hat)'), ('android', 'Android')], default=1, help_text='The target operating system for this file.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='release_file',
            field=models.FileField(upload_to=root.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(help_text='e.g., v1.0.1', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('version', 'os')},
        ),
    ]
