# Generated by Django 5.2.8 on 2025-11-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_release_os_alter_release_release_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='weblog',
            name='tags',
            field=models.ManyToManyField(to='root.tag'),
        ),
    ]
